openapi: 3.0.3
info:
  title: Cliente Service API
  version: 1.0.0
  description: Microservicio encargado de la gestión de clientes

servers:
  - url: http://localhost:8081

paths:

  /clientes:
    post:
      summary: Registrar un nuevo cliente
      tags:
        - Clientes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '201':
          description: Cliente creado correctamente

    get:
      summary: Listar todos los clientes
      tags: [Clientes]
      responses:
        '200':
          description: Lista de clientes
    put:
      summary: Actualizar cliente completo
      tags: [ Clientes ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Cliente actualizado

    patch:
      summary: Actualizar parcialmente cliente
      tags: [ Clientes ]
      responses:
        '200':
          description: Cliente modificado
      